-- ==========================================
-- NexInc Billing & Referral Columns Migration
-- ==========================================

-- 1. Add billing columns to public.profiles table
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS stripe_customer_id text,
  ADD COLUMN IF NOT EXISTS stripe_subscription_id text,
  ADD COLUMN IF NOT EXISTS billing_cycle text CONSTRAINT check_billing_cycle CHECK (billing_cycle IN ('monthly', 'yearly')),
  ADD COLUMN IF NOT EXISTS referral_code text;

-- Add comments for clarity
COMMENT ON COLUMN public.profiles.stripe_customer_id IS 'The unique customer identifier generated by Stripe.';
COMMENT ON COLUMN public.profiles.stripe_subscription_id IS 'The active subscription identifier generated by Stripe.';
COMMENT ON COLUMN public.profiles.billing_cycle IS 'The cycle of subscription: monthly or yearly.';
COMMENT ON COLUMN public.profiles.referral_code IS 'A unique random 10-character alphanumeric code for developer referrals.';

-- 2. Create the random 10-character alphanumeric generator function
CREATE OR REPLACE FUNCTION public.generate_random_code()
RETURNS text AS $$
DECLARE
  chars text := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  result text := '';
  i integer;
BEGIN
  FOR i IN 1..10 LOOP
    result := result || substr(chars, floor(random() * length(chars) + 1)::integer, 1);
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql;

-- 3. Update the handle_new_user trigger function to populate referral_code
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  ref_code text;
BEGIN
  -- Generate a random 10-character alphanumeric code
  ref_code := public.generate_random_code();

  INSERT INTO public.profiles (id, name, email, avatar_url, plan, referral_code)
  VALUES (
    new.id,
    COALESCE(
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      split_part(new.email, '@', 1)
    ),
    new.email,
    COALESCE(new.raw_user_meta_data->>'avatar_url', ''),
    'free',
    ref_code
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Backfill any existing profiles that do not have a referral code
UPDATE public.profiles
SET referral_code = public.generate_random_code()
WHERE referral_code IS NULL;
